name: Update Low Emission Zones Map

on:
  schedule:
    # Corre una vez por semana, el domingo a medianoche (UTC).
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-map:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 👈 Añade esta línea
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml

      - name: Run Python script to generate GeoJSON
        run: python generate_map.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          if [[ -n $(git status --porcelain data/low_emission_zones.geojson) ]]; then
            git add data/low_emission_zones.geojson
            git commit -m "chore: Update low emission zones data"
            git push
            echo "Changes committed and pushed successfully."
          else
            echo "No new changes to commit. The GeoJSON is up to date."
          fi
